// <auto-generated />
using System;
using System.Collections.Generic;
using FileService.Infrastructure.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FileService.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileService.Domain.MediaAssets.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("asset_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FinalKey")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("final_key");

                    b.Property<string>("RawKey")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Owner", "FileService.Domain.MediaAssets.MediaAsset.Owner#MediaOwner", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Context")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("context");

                            b1.Property<Guid>("EntityId")
                                .HasColumnType("uuid")
                                .HasColumnName("entity_id");
                        });

                    b.HasKey("Id")
                        .HasName("pk_media_asset");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_media_assets_status_created_at");

                    b.ToTable("media_assets", (string)null);

                    b.HasDiscriminator<string>("AssetType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FileService.Domain.PreviewAssets.PreviewAsset", b =>
                {
                    b.HasBaseType("FileService.Domain.MediaAssets.MediaAsset");

                    b.HasDiscriminator().HasValue("PREVIEW");
                });

            modelBuilder.Entity("FileService.Domain.VideoAssets.VideoAsset", b =>
                {
                    b.HasBaseType("FileService.Domain.MediaAssets.MediaAsset");

                    b.Property<string>("HlsRootKey")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("hls_root_key");

                    b.HasDiscriminator().HasValue("VIDEO");
                });

            modelBuilder.Entity("FileService.Domain.MediaAssets.MediaAsset", b =>
                {
                    b.OwnsOne("FileService.Domain.MediaAssets.ValueObjects.MediaData", "MediaData", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("media_assets");

                            b1.ToJson("media_data");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");

                            b1.OwnsOne("FileService.Domain.MediaAssets.ValueObjects.ContentType", "ContentType", b2 =>
                                {
                                    b2.Property<Guid>("MediaDataMediaAssetId");

                                    b2.Property<string>("Category")
                                        .IsRequired()
                                        .HasJsonPropertyName("category");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasJsonPropertyName("content_type");

                                    b2.HasKey("MediaDataMediaAssetId");

                                    b2.ToTable("media_assets");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaDataMediaAssetId");
                                });

                            b1.OwnsOne("FileService.Domain.MediaAssets.ValueObjects.ExpectedChunksCount", "ExpectedChunksCount", b2 =>
                                {
                                    b2.Property<Guid>("MediaDataMediaAssetId");

                                    b2.Property<int>("Value")
                                        .HasJsonPropertyName("expected_chunks_count");

                                    b2.HasKey("MediaDataMediaAssetId");

                                    b2.ToTable("media_assets");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaDataMediaAssetId");
                                });

                            b1.OwnsOne("FileService.Domain.MediaAssets.ValueObjects.FileName", "FileName", b2 =>
                                {
                                    b2.Property<Guid>("MediaDataMediaAssetId");

                                    b2.Property<string>("Extension")
                                        .IsRequired()
                                        .HasJsonPropertyName("extension");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasJsonPropertyName("name");

                                    b2.HasKey("MediaDataMediaAssetId");

                                    b2.ToTable("media_assets");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaDataMediaAssetId");
                                });

                            b1.OwnsOne("FileService.Domain.MediaAssets.ValueObjects.FileSize", "Size", b2 =>
                                {
                                    b2.Property<Guid>("MediaDataMediaAssetId");

                                    b2.Property<long>("Value")
                                        .HasJsonPropertyName("size");

                                    b2.HasKey("MediaDataMediaAssetId");

                                    b2.ToTable("media_assets");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaDataMediaAssetId");
                                });

                            b1.Navigation("ContentType")
                                .IsRequired();

                            b1.Navigation("ExpectedChunksCount")
                                .IsRequired();

                            b1.Navigation("FileName")
                                .IsRequired();

                            b1.Navigation("Size")
                                .IsRequired();
                        });

                    b.Navigation("MediaData")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
